- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic:
        elastic_host: 10.100.11.140
        elastic_port: 5643
        elastic_username: admin
        elastic_password: P@ssw0rd
        elastic_index_pattern: heartbeat-*
        query: |
          term:
            monitor.id: httpd-monitor
        interval: 30
  rules:
    - name: Heartbeat monitor check
      condition: event.ecs is defined and event.state.status == "down"
      action:
        run_job_template:
          name: "Restart HTTPd"
          organization: Default
      logging:
        level: debug
        message: "Condition met: {{ event.state.status }}"
